sudo: false

matrix:
  fast_finish: true
  include:
    - os: linux
      language: c++
      env: CMAKE_COMPILER=clang++-3.7
      addons:
        apt:
          packages:
            - clang-3.7
            - libboost1.58-dev
          sources:
            - boost-latest
    - os: linux
      language: c++
      env: CMAKE_COMPILER=g++-5
      addons:
        apt:
          packages:
            - g++-5
            - libboost1.58-dev
          sources:
            - ubuntu-toolchain-r-test
            - boost-latest
    - os: osx
      language: objective-c
      env: CMAKE_COMPILER=clang++

install:

script: CXX=${CMAKE_COMPILER} ./build_and_test.sh
